'use strict';

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const {
  upsertKgVaultHash,
  getKgVaultHash,
  queryKnowledgeEntries,
} = require('./queries');

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const CATEGORY_FILES = {
  domain:        'domain.md',
  stack:         'stack.md',
  schema:        'schema.md',
  api:           'api.md',
  feature:       'features.md',
  architecture:  'architecture.md',
  convention:    'conventions.md',
  decision:      'decisions.md',
  footgun:       'footguns.md',
  contract:      'contracts.md',
  error_pattern: 'error-patterns.md',
};

const CATEGORY_TITLES = {
  domain:        'Domain & Business Logic',
  stack:         'Tech Stack',
  schema:        'Database Schema',
  api:           'API Contracts',
  feature:       'Features & Business Logic',
  architecture:  'Architecture',
  convention:    'Conventions',
  decision:      'Decisions',
  footgun:       'Footguns',
  contract:      'Contracts',
  error_pattern: 'Error Patterns',
};

const KNOWLEDGE_INCLUDE = '@.claude/knowledge/index.md';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function isGitRepo(dir) {
  try { return fs.statSync(path.join(dir, '.git')).isDirectory(); }
  catch { return false; }
}

function sha256(content) {
  return crypto.createHash('sha256').update(content).digest('hex');
}

/**
 * Stable hash: strips timestamp lines so files aren't rewritten when only
 * timestamps change (reuses the same pattern as op-vault-generator.js).
 */
function stableHash(content) {
  const stable = content
    .replace(/^generated_at:.*$/m, '')
    .replace(/^> Generated at.*$/m, '')
    .replace(/^<!-- generated_at:.*-->$/m, '');
  return sha256(stable);
}

// ---------------------------------------------------------------------------
// renderCategoryPage
// ---------------------------------------------------------------------------

/**
 * Renders markdown for one category file.
 *
 * @param {string} category
 * @param {Array}  entries — knowledge_entries rows
 * @returns {string}
 */
function renderCategoryPage(category, entries) {
  const title = CATEGORY_TITLES[category] || category;
  const now = new Date().toISOString();

  const lines = [
    '<!-- Auto-generated by Open Pulse. Do not edit. -->',
    `<!-- generated_at: ${now} -->`,
    '',
    `# ${title}`,
    '',
  ];

  for (const entry of entries) {
    let tags = [];
    try { tags = JSON.parse(entry.tags || '[]'); } catch { /* ignore */ }

    lines.push(`## ${entry.title}`, '');
    lines.push(entry.body || '', '');

    if (entry.source_file) {
      lines.push(`_Source: \`${entry.source_file}\`_`, '');
    }

    if (tags.length > 0) {
      lines.push(`_Tags: ${tags.map(t => `\`${t}\``).join(', ')}_`, '');
    }
  }

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// renderIndexPage
// ---------------------------------------------------------------------------

/**
 * Renders index.md with table of contents grouped by category.
 *
 * @param {string} projectName
 * @param {Object} entriesByCategory — { [category]: entries[] }
 * @returns {string}
 */
function renderIndexPage(projectName, entriesByCategory) {
  const now = new Date().toISOString();

  const lines = [
    '<!-- Auto-generated by Open Pulse. Do not edit. -->',
    `<!-- generated_at: ${now} -->`,
    '',
    `# Knowledge Base — ${projectName}`,
    '',
    `> Generated at ${now}`,
    '',
  ];

  const categories = Object.keys(entriesByCategory).sort();

  if (categories.length === 0) {
    lines.push('_No knowledge entries yet._', '');
    return lines.join('\n');
  }

  for (const cat of categories) {
    const entries = entriesByCategory[cat];
    if (!entries || entries.length === 0) continue;

    const catTitle = CATEGORY_TITLES[cat] || cat;
    const fileName = CATEGORY_FILES[cat] || `${cat}.md`;

    lines.push(`## ${catTitle}`, '');
    for (const entry of entries) {
      lines.push(`- [${entry.title}](${fileName})`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// ensureClaudeMdInclude
// ---------------------------------------------------------------------------

/**
 * If the project has a CLAUDE.md, ensure it includes @.claude/knowledge/index.md.
 * Inserts after the first heading line. Does nothing if CLAUDE.md doesn't exist
 * or the include is already present.
 */
function ensureClaudeMdInclude(projectDir) {
  const claudeMdPath = path.join(projectDir, 'CLAUDE.md');
  let content;
  try { content = fs.readFileSync(claudeMdPath, 'utf8'); } catch { return; }

  if (content.includes(KNOWLEDGE_INCLUDE)) return;

  // Insert after the first line (heading)
  const firstNewline = content.indexOf('\n');
  if (firstNewline === -1) {
    content += '\n\n' + KNOWLEDGE_INCLUDE + '\n';
  } else {
    content = content.slice(0, firstNewline + 1) + '\n' + KNOWLEDGE_INCLUDE + '\n' + content.slice(firstNewline + 1);
  }

  fs.writeFileSync(claudeMdPath, content, 'utf8');
}

// ---------------------------------------------------------------------------
// renderKnowledgeVault
// ---------------------------------------------------------------------------

/**
 * Generates .md files per category into <project_dir>/.claude/knowledge/.
 * Uses content-hash dedup (kg_vault_hashes) to skip unchanged files.
 * Only renders for git repos.
 *
 * @param {import('better-sqlite3').Database} db
 * @param {string} projectId
 * @returns {{ filesWritten: number, filesSkipped: number }}
 */
function renderKnowledgeVault(db, projectId) {
  const project = db.prepare('SELECT * FROM cl_projects WHERE project_id = ?').get(projectId);
  if (!project || !project.directory || !isGitRepo(project.directory)) {
    return { filesWritten: 0, filesSkipped: 0 };
  }

  const vaultDir = path.join(project.directory, '.claude', 'knowledge');
  fs.mkdirSync(vaultDir, { recursive: true });

  // Query all active entries for this project
  const { items: allEntries } = queryKnowledgeEntries(db, {
    projectId,
    status: 'active',
    perPage: 1000,
  });

  // Group entries by category
  const entriesByCategory = {};
  for (const entry of allEntries) {
    if (!entriesByCategory[entry.category]) {
      entriesByCategory[entry.category] = [];
    }
    entriesByCategory[entry.category].push(entry);
  }

  let filesWritten = 0;
  let filesSkipped = 0;

  // Render one file per category
  for (const [category, entries] of Object.entries(entriesByCategory)) {
    const fileName = CATEGORY_FILES[category] || `${category}.md`;
    const relPath = fileName;
    const fullPath = path.join(vaultDir, relPath);

    const content = renderCategoryPage(category, entries);
    const hash = stableHash(content);
    const stored = getKgVaultHash(db, projectId, relPath);

    if (stored === hash) {
      filesSkipped++;
      continue;
    }

    fs.writeFileSync(fullPath, content, 'utf8');
    upsertKgVaultHash(db, { project_id: projectId, file_path: relPath, content_hash: hash });
    filesWritten++;
  }

  // Render index.md
  const projectName = project.name || projectId;
  const indexContent = renderIndexPage(projectName, entriesByCategory);
  const indexRelPath = 'index.md';
  const indexHash = stableHash(indexContent);
  const storedIndex = getKgVaultHash(db, projectId, indexRelPath);

  if (storedIndex === indexHash) {
    filesSkipped++;
  } else {
    fs.writeFileSync(path.join(vaultDir, indexRelPath), indexContent, 'utf8');
    upsertKgVaultHash(db, { project_id: projectId, file_path: indexRelPath, content_hash: indexHash });
    filesWritten++;
  }

  // Ensure CLAUDE.md references the knowledge index
  ensureClaudeMdInclude(project.directory);

  return { filesWritten, filesSkipped };
}

// ---------------------------------------------------------------------------
// Exports
// ---------------------------------------------------------------------------

module.exports = {
  CATEGORY_FILES,
  CATEGORY_TITLES,
  renderCategoryPage,
  renderIndexPage,
  renderKnowledgeVault,
};
